import turtle
t = turtle.Pen()
turtle.shape('turtle')
turtle.color('black')
turtle.up()
turtle.goto(100, 0)
turtle.left(90)
turtle.down()
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.up()
turtle.goto(-30, 50)
turtle.down()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(15)
turtle.end_fill()
turtle.up()
turtle.goto(60, 50)
turtle.down()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(15)
turtle.end_fill()
turtle.up()
turtle.goto(0, 30)
turtle.down()
turtle.color('black')
turtle.pensize(8)
turtle.left(180)
turtle.forward(50)
turtle.up()
turtle.goto(70, -10)
turtle.color('red')
turtle.down()
turtle.circle(-70, 180, 30)
turtle.hideturtle()
turtle.exitonclick()
